version: '3.9'
services:
  web:
    platform: 'linux/amd64'
    image: memetapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - '3001:3000'

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio_storage:/data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
    command: server --console-address ":9090" /data

volumes:
  db: {}
  minio_storage: {}

networks:
  default:
    name: memetapp
    external: true
